# File generated from Twilio's OpenAPI spec — do not edit manually
defmodule Twilio.Resources.Verify.V2.Service.Entity do
  @moduledoc """


  SID prefix: `YE`

  Parent: `/Services/{Sid}`

  ## Sub-resources
  - `challenges` — `/v2/Services/{service_sid}/Entities/{identity}/Challenges`
  - `factors` — `/v2/Services/{service_sid}/Entities/{identity}/Factors`
  - `new_factors` — `/v2/Services/{service_sid}/Entities/{identity}/Factors`

  ## Properties

  | Field | Description |
  |-------|-------------|
  | `account_sid` | The unique SID identifier of the Account. |
  | `date_created` | The date that this Entity was created, given in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.. Format: date-time |
  | `date_updated` | The date that this Entity was updated, given in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.. Format: date-time |
  | `identity` | The unique external identifier for the Entity of the Service. This identifier should be immutable, not PII, length between 8 and 64 characters, and generated by your external system, such as your user's UUID, GUID, or SID. It can only contain dash (-) separated alphanumeric characters.. PII: standard |
  | `links` | Contains a dictionary of URL links to nested resources of this Entity.. Format: uri-map |
  | `service_sid` | The unique SID identifier of the Service. |
  | `sid` | A 34 character string that uniquely identifies this Entity. |
  | `url` | The URL of this resource.. Format: uri |
  """

  @type t :: %__MODULE__{
          account_sid: String.t() | nil,
          date_created: String.t() | nil,
          date_updated: String.t() | nil,
          identity: String.t() | nil,
          links: map() | nil,
          service_sid: String.t() | nil,
          sid: String.t() | nil,
          url: String.t() | nil
        }

  defstruct [
    :account_sid,
    :date_created,
    :date_updated,
    :identity,
    :links,
    :service_sid,
    :sid,
    :url
  ]

  @object_name "verify.v2.service.entity"
  def object_name, do: @object_name

  @sid_prefix "YE"
  def sid_prefix, do: @sid_prefix
end
