# File generated from Twilio's OpenAPI spec — do not edit manually
defmodule Twilio.Insights.V1.Conference.ParticipantService do
  @moduledoc """
  Service for Participant API operations.

  Operations: `list`, `fetch`
  """

  alias Twilio.Client
  alias Twilio.Deserializer

  @doc """
  Get a list of Conference Participants Summaries for a Conference.

  Operation: `ListConferenceParticipant` | Tags: InsightsV1ConferenceParticipant

  ## Query Parameters

  | Parameter | Type | Description |
  |-----------|------|-------------|
  | `ParticipantSid` | string | The unique SID identifier of the Participant. |
  | `Label` | string | User-specified label for a participant. |
  | `Events` | string | Conference events generated by application or participant activity; e.g. `hold`, `mute`, etc. |
  """
  @spec list(Client.t(), String.t(), map(), keyword()) ::
          {:ok, Twilio.Page.t()} | {:ok, map(), map()} | :ok | {:error, Twilio.Error.t()}
  def list(client, conference_sid, params \\ %{}, opts \\ []) do
    case Client.request(client, :get, "/v1/Conferences/#{conference_sid}/Participants",
           params: params,
           opts: opts,
           base_url: "https://insights.twilio.com"
         ) do
      {:ok, data} ->
        page = Twilio.Page.from_response(data, "participants")

        {:ok,
         %{
           page
           | items:
               Deserializer.deserialize_list(
                 page.items,
                 Twilio.Resources.Insights.V1.Conference.Participant
               )
         }}

      error ->
        error
    end
  end

  @doc "Stream: Get a list of Conference Participants Summaries for a Conference. (lazy auto-pagination)."
  @spec stream(Client.t(), String.t(), map(), keyword()) :: Enumerable.t()
  def stream(client, conference_sid, params \\ %{}, opts \\ []) do
    Twilio.Page.stream(
      fn page_opts ->
        list(client, conference_sid, Map.merge(params, page_opts), opts)
      end,
      "participants"
    )
  end

  @doc """
  Get a specific Conference Participant Summary for a Conference.

  Operation: `FetchConferenceParticipant` | Tags: InsightsV1ConferenceParticipant

  ## Query Parameters

  | Parameter | Type | Description |
  |-----------|------|-------------|
  | `Events` | string | Conference events generated by application or participant activity; e.g. `hold`, `mute`, etc. |
  | `Metrics` | string | Object. Contains participant call quality metrics. |
  """
  @spec fetch(Client.t(), String.t(), String.t(), keyword()) ::
          {:ok, Twilio.Resources.Insights.V1.Conference.Participant.t()}
          | {:ok, map(), map()}
          | :ok
          | {:error, Twilio.Error.t()}
  def fetch(client, conference_sid, sid, opts \\ []) do
    with {:ok, data} <-
           Client.request(client, :get, "/v1/Conferences/#{conference_sid}/Participants/#{sid}",
             opts: opts,
             base_url: "https://insights.twilio.com"
           ) do
      {:ok, Deserializer.deserialize(data, Twilio.Resources.Insights.V1.Conference.Participant)}
    end
  end
end
