# File generated from Twilio's OpenAPI spec — do not edit manually
defmodule Twilio.Resources.Api.V2010.Call.Notification do
  @moduledoc """
  Error notifications for calls

  SID prefix: `NO`

  Parent: `/Accounts/{AccountSid}/Calls/{Sid}.json`

  ## Properties

  | Field | Description |
  |-------|-------------|
  | `account_sid` | The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Call Notification resource. |
  | `api_version` | The API version used to create the Call Notification resource. |
  | `call_sid` | The SID of the [Call](https://www.twilio.com/docs/voice/api/call-resource) the Call Notification resource is associated with. |
  | `date_created` | The date and time in GMT that the resource was created specified in [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt) format.. Format: date-time-rfc-2822 |
  | `date_updated` | The date and time in GMT that the resource was last updated specified in [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt) format.. Format: date-time-rfc-2822 |
  | `error_code` | A unique error code for the error condition that is described in our [Error Dictionary](https://www.twilio.com/docs/api/errors). |
  | `log` | An integer log level that corresponds to the type of notification: `0` is ERROR, `1` is WARNING. |
  | `message_date` | The date the notification was actually generated in [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt) format. Message buffering can cause this value to differ from `date_created`.. Format: date-time-rfc-2822 |
  | `message_text` | The text of the notification. |
  | `more_info` | The URL for more information about the error condition. This value is a page in our [Error Dictionary](https://www.twilio.com/docs/api/errors).. Format: uri |
  | `request_method` | The HTTP method used to generate the notification. If the notification was generated during a phone call, this is the HTTP Method used to request the resource on your server. If the notification was generated by your use of our REST API, this is the HTTP method used to call the resource on our servers.. Values: `GET`, `POST`. Format: http-method |
  | `request_url` | The URL of the resource that generated the notification. If the notification was generated during a phone call, this is the URL of the resource on your server that caused the notification. If the notification was generated by your use of our REST API, this is the URL of the resource you called.. Format: uri |
  | `request_variables` | The HTTP GET or POST variables we sent to your server. However, if the notification was generated by our REST API, this contains the HTTP POST or PUT variables you sent to our API. |
  | `response_body` | The HTTP body returned by your server. |
  | `response_headers` | The HTTP headers returned by your server. |
  | `sid` | The unique string that that we created to identify the Call Notification resource. |
  | `uri` | The URI of the resource, relative to `https://api.twilio.com`. |
  """

  @type t :: %__MODULE__{
          account_sid: String.t() | nil,
          api_version: String.t() | nil,
          call_sid: String.t() | nil,
          date_created: String.t() | nil,
          date_updated: String.t() | nil,
          error_code: String.t() | nil,
          log: String.t() | nil,
          message_date: String.t() | nil,
          message_text: String.t() | nil,
          more_info: String.t() | nil,
          request_method: String.t() | nil,
          request_url: String.t() | nil,
          request_variables: String.t() | nil,
          response_body: String.t() | nil,
          response_headers: String.t() | nil,
          sid: String.t() | nil,
          uri: String.t() | nil
        }

  defstruct [
    :account_sid,
    :api_version,
    :call_sid,
    :date_created,
    :date_updated,
    :error_code,
    :log,
    :message_date,
    :message_text,
    :more_info,
    :request_method,
    :request_url,
    :request_variables,
    :response_body,
    :response_headers,
    :sid,
    :uri
  ]

  @object_name "api.v2010.account.call.call_notification-instance"
  def object_name, do: @object_name

  @sid_prefix "NO"
  def sid_prefix, do: @sid_prefix
end
